### ISSUE TITLE
Read .MDL files

### ISSUE THREAD

**Issue by HarrisSym** [GameTechDev/FaceMapping2#3]
Is there a way/program to visualise the code of the .MDL files?

**Comment by wheresthecode** [comment]
Hi Harris,

Indeed the fbx files are corrupt. Unfortunately I don't have the originals. The best approach to recovering the data is to have the sample load the .MDL files and then export them to a universal model format. The sample includes code that can export to the OBJ model format, so you might be able to use that code to achieve this.

-Joe
